name: Continuous Deployment

on:
    push:
      branches:
        - release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Download Wix
        uses: i3h/download-release-asset@v1
        if: matrix.os == 'windows-latest'
        with:
          owner: wixtoolset
          repo: wix3
          tag: wix3112rtm
          file: wix311-binaries.zip

      - name: Decompress Wix
        uses: DuckSoft/extract-7z-action@v1.0
        if: matrix.os == 'windows-latest'
        with:
          pathSource: wix311-binaries.zip
          pathTarget: ./target/wix

      - name: Add Wix to Path
        run: echo "$HOME/target/wix" >> $GITHUB_PATH
        if: matrix.os == 'windows-latest'

      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'liberica'
          java-package: jdk+fx
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml -DcreateReleases=true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ matrix.os }} Development Build
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          make_latest: true
          generate_release_notes: false
          target_commitish: release
          token: ${{ secrets.GITHUB_TOKEN}}
          files: |
            ./target/*.msi
            ./target/*.deb
