name: Continuous Deployment

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
      - name: Download Wix
        uses: i3h/download-release-asset@v1
        if: matrix.os == 'windows-latest'
        with:
          owner: wixtoolset
          repo: wix3
          tag: wix3112rtm
          file: wix311-binaries.zip

      - name: Decompress Wix
        uses: DuckSoft/extract-7z-action@v1.0
        if: matrix.os == 'windows-latest'
        with:
          pathSource: wix311-binaries.zip
          pathTarget: ./target/wix

      - name: Add Wix to Path
        run: echo "$HOME/target/wix" >> $GITHUB_PATH
        if: matrix.os == 'windows-latest'

      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'liberica'
          java-package: jdk+fx
          cache: 'maven'

      - name: Extract Version Number from Tag
        id: extract_version
        run: |
          TAG=${GITHUB_REF##*/}
          VERSION=${TAG#v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
        shell: bash

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml -DcreateRelease=true -Dapp.version=${{ env.VERSION }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }} Release
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          make_latest: true
          generate_release_notes: false
          token: ${{ secrets.GITHUB_TOKEN}}
          files: |
            ./target/*.msi
            ./target/*.deb
